### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by iksaku**
^^^

This is kinda different to the existing one... As this isn't translated by a machine-like schema :P

### CODE REVIEW

**Comment by JoahDave** [comment]
Sigh

**Comment by PEMapModder** [comment]
Conflicts.

**Comment by 64FF00** [comment]
@iksaku Can you pls change the filename to messages-sp.yml? Ty!

**Comment by iksaku** [comment]
@PEMapModder I know :P 
@64FF00 I will do it later today I get home :3

**Comment by iksaku** [comment]
@64FF00 Done :P it appears that I can edit file names on mobile too xD

**Comment by JoahDave** [comment]
@iksaku I've found that the "Desktop version" button is quite effective.

**Comment by JoahDave** [comment]
@iksaku Spanish was not my first language. No need to say "FIXED ALMOST EVERYTHING".

**Comment by iksaku** [comment]
@JoahDave I didn't told that... It was @64FF00 :P also, I know Spanish is a hard language due to its complex nexus and suffix... So this would fix that ;)

**Comment by JoahDave** [comment]
@iksaku Thanks! <3

**Pull request closed without merging**
