### PR TITLE
Config override bug fix

### PR DESCRIPTION
**Pull request by dktapps**
Fixes bug where config would get overridden no matter if it existed or not, resulting in properties always being reset to defaults. Most notably disable-op would turn itself back to true every time I restarted my server.

### CODE REVIEW

**Comment by Mike4l6** [comment]
how do i get this?

**Comment by dktapps** [comment]
@Mike4l6 Try setting disable-op to false in config.yml. Unless you apply this patch, it resets itself to True when the server reloads/restarts.

**Comment by Mike4l6** [comment]
I meant how do I apply the patch?

**Comment by dktapps** [comment]
I have a patched phar you can download here:
https://drive.google.com/file/d/0By8Xy-T6X5Z8TzJ6TldiRmRWVFk/view?usp=drivesdk
Delete old PurePerms phar and replace with this one.

**Comment by Mike4l6** [comment]
this is issue is still happening :?

**Comment by dktapps** [comment]
@Mike4l6 unfortunately. My patched version fixes the problem

**Comment by dktapps** [comment]
Rebased and got rid of that merge commit.

**Comment by dktapps** [comment]
Invalid? Really? Guess I'll have to find myself a different permissions plugin then

**Comment by 64FF00** [comment]
@dktapps https://github.com/iTXTech/Genisys/issues/1590#issuecomment-239102294

**Comment by dktapps** [comment]
@64FF00 I replied under the same issue

**Comment by Andrew1481432** [comment]
Found a bug provider mysql do not prefix and timings pct 3% fix provider mysql

**Comment by Andrew1481432** [comment]
@64FF00 Found a bug provider mysql do not prefix and timings pct 3% fix provider mysql

**Pull request closed without merging**
