### PR TITLE
Update messages-ru.yml and fix more langues

### PR DESCRIPTION
**Pull request by Pub4Game**
:cake:

### CODE REVIEW

**Comment by Pub4Game** [comment]
@64FF00 Why my changes were not accepted?

**Comment by Pub4Game** [comment]
@64FF00 =_= Perenesite my changes again to the master branch

**Comment by 64FF00** [comment]
@Pub4Game ???

**Comment by 64FF00** [comment]
@Pub4Game https://github.com/PurePlugins/PurePerms/commit/d9a00b19b9ffb9e19b38a97f3ef9c07afc5355ab

**Comment by Pub4Game** [comment]
@64FF00 ^_^

**Pull request merged**
