### PR TITLE
Messages-RU.yml update

### PR DESCRIPTION
**Pull request by 0-Eclipse-0**
Finished translating the file to Russian.

### CODE REVIEW

**Comment by Lucario2** [comment]
Nice job! :)

**Comment by 64FF00** [comment]
@0-Eclipse-0 @Lucario2 Nice job woohooooooo

**Comment by Lucario2** [comment]
...

**Comment by Lucario2** [comment]
YEAH IKR!

**Comment by Lucario2** [comment]
You are hell of a programmer....

**Comment by 64FF00** [comment]
@Lucario2 :D :heart:

**Comment by Lucario2** [comment]
I like you. You are nice to me.

**Comment by Lucario2** [comment]
YOU DA BEST CODA EVA

**Comment by Lucario2** [comment]
XD

**Comment by 64FF00** [comment]
@Lucario2 Thank you sirrr

**Comment by Lucario2** [comment]
You have kik?

**Comment by Lucario2** [comment]
No one treats me like a person. everyone treats me like shit.

**Comment by Lucario2** [comment]
@peratx always ignores me

**Comment by Lucario2** [comment]
but she was nice for a little...

**Comment by Lucario2** [comment]
@64FF00 Can I talk to you in gitter?

**Comment by 0-Eclipse-0** [comment]
@64FF00 Couldn't pass up the opportunity to help an old friend.

**Pull request merged**
